routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
    'divisi'=>'DivisiController',
    'subdivisi'=>'SubdivisiController',
    'user'=>'UserController',
    'event'=>'EventController',
    'event2'=>'Event2Controller',
    'attach' => 'AttachmentController',
    'reportevent' => 'ReportController'
]);

Route::post('approve/{id}','EventController@approve')->name('approve');

Route::post('reject/{id}','EventController@reject')->name('reject');

Route::get('user.ambil','UserController@ambil');
Route::get('user/hapus/{id}','UserController@hapus');
Route::get('user/edit/{id}','UserController@edit');
Route::patch('user/update/{id}','UserController@update');

app/Divisi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Divisi extends Model
{
   protected $guarded = [];
}

app/Http/Controllers/DivisiController.php
<?php

namespace App\Http\Controllers;

use App\Divisi;
use Illuminate\Http\Request;

class DivisiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.divisi.index',['data'=>Divisi::paginate(10)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.divisi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Divisi::create($request->all());
        return redirect()->route('divisi.index')->with('message','Berhasil Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Divisi  $divisi
     * @return \Illuminate\Http\Response
     */
    public function show(Divisi $divisi)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Divisi  $divisi
     * @return \Illuminate\Http\Response
     */
    public function edit(Divisi $divisi)
    {
        return view('pages.divisi.edit',['data'=>$divisi]);
    }

    /**
     * Update th=e specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Divisi  $divisi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Divisi $divisi)
    {
        $divisi->update($request->except('_token','_method'));
        return redirect()->route('divisi.index')->with('message','Berhasil Dirubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Divisi  $divisi
     * @return \Illuminate\Http\Response
     */
    public function destroy(Divisi $divisi)
    {
        $divisi->delete();

        return redirect()->route('divisi.index')->with('message','Berhasil Dihapus');
    }
}

resources/views/pages/divisi/create.blade.php
@extends('layouts.temp')
@section('icon')
     <i class="feather icon-plus bg-c-blue"></i>
@endsection
@section('title')
    Tambah Divisi
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="#!">Divisi</a> </li>
    <li class="breadcrumb-item"><a href="#!">Tambah Divisi</a> </li>
@endsection
@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            Tambah Divisi
        </div>
        <div class="card-body">
            <form action="{{route('divisi.store')}}" method="post">
                @csrf 
                <div class="form-group">
                    <label for="my-input">Nama</label>
                    <input id="my-input" class="form-control" type="text" name="name" required>
                </div>
                <button type="submit" class="btn btn-success">Simpan</button>
                <a href="{{route('divisi.index')}}">
                    <button type="button" class="btn btn-secondary">
                        Kembali
                    </button>
                </a>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/pages/divisi/edit.blade.php
@extends('layouts.temp')
@section('icon')
     <i class="feather icon-plus bg-c-blue"></i>
@endsection
@section('title')
    Tambah Divisi
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="#!">Divisi</a> </li>
    <li class="breadcrumb-item"><a href="#!">Tambah Divisi</a> </li>
@endsection
@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
        </div>
        <div class="card-body">
            <form action="{{route('divisi.update',$data)}}" method="post">
                @csrf @method('patch')
                <div class="form-group">
                    <label for="my-input">Nama</label>
                    <input id="my-input" class="form-control" type="text" name="name" required value="{{$data->name}}">
                </div>
                <button type="submit" class="btn btn-success">Edit</button>
                <a href="{{route('divisi.index')}}">
                    <button type="button" class="btn btn-secondary">
                        Kembali
                    </button>
                </a>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/pages/divisi/index.blade.php
@extends('layouts.temp')
@section('icon')
     <i class="feather icon-tag bg-c-blue"></i>
@endsection
@section('title')
    Divisi
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="#!">Divisi</a> </li>
@endsection
@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <H3>Divisi
            <a href="{{route('divisi.create')}}" class="btn btn-success btn-sm float-right">Tambah</a>
            </H3>
        </div>
    </div>

@foreach ($data as $show)
    <div class="card mb-3 comp-card">
        <div class="card-body">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="f-w-700 text-c-black">{{ $show->name }}</h3>
                </div>
                <div class="col-auto">
                    <a href="{{route('divisi.edit',$show)}}" class="btn btn-primary btn-sm waves-effect waves-light text-white"><span class="fas fa-edit"></span></a>
                    <a  class="btn btn-danger btn-sm waves-effect waves-light text-white"
                    onclick="event.preventDefault();
                    $('#delete-form').attr('action','{{route('divisi.destroy',$show)}}')
                    document.getElementById('delete-form').submit();"
                    ><span class="fas fa-trash"></span></a>
                    <form id="delete-form" action="" method="POST" style="display: none;">
                        @csrf @method('delete')
                    </form>
                </div>
            </div>
        </div>
    </div>

@endforeach
{{ $data->links() }}

</div>
@endsection