routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
    'divisi'=>'DivisiController',
    'subdivisi'=>'SubdivisiController',
    'user'=>'UserController',
    'event'=>'EventController',
    'event2'=>'Event2Controller',
    'attach' => 'AttachmentController',
    'reportevent' => 'ReportController'
]);

Route::post('approve/{id}','EventController@approve')->name('approve');

Route::post('reject/{id}','EventController@reject')->name('reject');

Route::get('user.ambil','UserController@ambil');
Route::get('user/hapus/{id}','UserController@hapus');
Route::get('user/edit/{id}','UserController@edit');
Route::patch('user/update/{id}','UserController@update');

app/Http/Controllers/Event2Controller.php
<?php

namespace App\Http\Controllers;

use App\Event;
use App\Report;
use Auth;
use App\Attachment;
use Illuminate\Http\Request;
use Carbon\Carbon;

class Event2Controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Event::where('status', 'approve')->orWhere('status', 'rejected')->latest()->paginate(10);

        return view('pages.event.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/event2/create.blade.php
@extends('layouts.temp')
@section('icon')
<i class="feather icon-plus bg-c-blue"></i>
@endsection
@section('title')
Tambah Events
@endsection
@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{route('event.index')}}">Events</a> </li>
<li class="breadcrumb-item"><a href="#!">Tambah Events</a> </li>
@endsection
@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            Tambah Events
            <a href="{{route('event.index')}}" class="btn btn-secondary btn-sm float-right">Kembali</a>
        </div>
        <div class="card-body">
            <form action="{{route('event.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
                <div class="form-group">
                    <label for="my-input">Judul</label>
                    <input id="my-input" class="form-control" type="text" name="title" required>
                </div>
                <label for="">Tipe</label>
                <div class="form-radio">
                    <div class="radio radio-inline">
                        <label>
                            <input type="radio" name="type" checked="checked" value="rutinitas">
                            <i class="helper"></i>Rutinitas
                        </label>
                    </div>
                    <div class="radio radio-inline">
                        <label>
                            <input type="radio" name="type" value="khusus">
                            <i class="helper"></i>Khusus
                        </label>
                    </div>
                </div>
                <br>
                <div class="form-group">
                    <label for="my-input">Tanggal Mulai</label>
                    <input id="my-input" class="form-control" type="datetime-local" name="start" required>
                </div>
                <div class="form-group">
                    <label for="my-input">Tanggal Akhir</label>
                    <input id="my-input" class="form-control" type="datetime-local" name="end" required>
                </div>
                <div class="form-group">
                    <label for="my-input">Deskripsi</label>
                    <textarea name="description" class="form-control" id="" cols="30" rows="10"></textarea>
                </div>
                <label for="">Lampiran ( <i>Optional</i> )</label>
                <input type="file" class="dropify" data-height="300" name="attachment" data-max-file-size="10M" data-allowed-file-extensions="pdf png jpg jpeg doc docx xls xlxs"  />
                <br>
                <button type="submit" class="btn btn-success">Simpan</button>    
            </form>
            
        </div>
    </div>
</div>
@endsection

resources/views/pages/event2/detail.blade.php
@extends('layouts.temp')
@section('icon')
<i class="feather icon-info bg-c-blue"></i>
@endsection
@section('title')
Detail Event
@endsection
@section('breadcrumb')
<li class="breadcrumb-item"><a href="#!">Event</a> </li>
<li class="breadcrumb-item"><a href="#!">Detail Event</a> </li>
@endsection
@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <H3>Detail Event
                <a href="{{route('event.index')}}" class="btn btn-secondary btn-sm float-right">kembali</a>
            </H3>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <div class="card-header-left">
                <h4> Event</h4>
            </div>
            <div class="card-header-right">
                <ul class="list-unstyled card-option">
                    <li class="first-opt"><i class="feather icon-chevron-left open-card-option"></i></li>
                    <li><i class="feather icon-maximize full-card"></i></li>
                    <li><i class="feather icon-minus minimize-card"></i></li>
                    <li><i class="feather icon-refresh-cw reload-card"></i></li>
                    
                    <li><i class="feather icon-chevron-left open-card-option"></i></li>
                </ul>
            </div>
        </div>
        <div class="card-block">
            <table class="table table-responsive">
                <tr>
                    <th>Author</th>
                    <td>:</td>
                    <td>{{ $data->user->name }}</td>
                </tr>
                <tr>
                    <th>Judul</th>
                    <td>:</td>
                    <td>{{ $data->title }}</td>
                </tr>
                <tr>
                    <th>Tipe</th>
                    <td>:</td>
                    <td>{{ $data->type }}</td>
                </tr>
                <tr>
                    <th>Tanggal Mulai</th>
                    <td>:</td>
                    <td>{{ $data->start }}</td>
                </tr>
                <tr>
                    <th>Tanggal Akhir</th>
                    <td>:</td>
                    <td>{{ $data->end }}</td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td>:</td>
                    <td>
                        @if ($data->status == 'waiting')
                        <div class="badge badge-secondary">Menunggu Dikonfirmasi</div>   
                        @elseif ($data->status == 'approve')
                        <div class="badge badge-info">Sudah Dikonfirmasi</div>    
                        @elseif ($data->status == 'rejected')
                        <div class="badge badge-danger">Pengajuan Ditolak</div>    
                        @elseif ($data->status == 'proccess')
                        <div class="badge badge-warning">Berlangsung</div> 
                        @elseif ($data->status == 'done')
                        <div class="badge badge-success">Selesai</div>    
                        @endif
                        
                    </td>
                </tr>
            </table>
            <br>
            @if (Auth::user()->role == 'admin')
                @if ($data->status == 'waiting')
                    <div class="row">
                        <div class="col-md-6">
                            <form action="{{route('approve',$data->id)}}" method="post">
                                @csrf
                                <button type="submit" class="btn btn-primary btn-block"><i class="fas fa-check-circle"></i>Approve</button>
                            </form>
                        </div>
                        <div class="col-md-6">
                            <form action="{{route('reject',$data->id)}}" method="post">
                                @csrf
                                <button type="submit" class="btn btn-danger btn-block"><i class="fas fa-close"></i>Reject</button>
                            </form>
                        </div>
                    </div>    
                @endif
            @elseif (Auth::user()->role == 'user')
                
            @endif
            
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h4>Lampiran
                @if (Auth::user()->id == $data->user_id || Auth::user()->role == 'admin')
                <a 
                class="btn btn-success waves-effect btn-sm float-right"
                data-toggle="modal"
                data-target="#default-Modal"><i class="text-white fa fa-plus-circle"></i></a>
                    
                @endif
                
                <div class="modal fade" id="default-Modal" tabindex="-1"
                role="dialog">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title"> Tambah lampiran</h4>
                                <button type="button" class="close"
                                    data-dismiss="modal"
                                    aria-label="Close">
                                    <span
                                        aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <form action="{{route('attach.store')}}" method="POST" enctype="multipart/form-data">
                                @csrf
                            <div class="modal-body">
                                <label for="">Lampiran </label>
                                <input type="hidden" name="event_id" value="{{$data->id}}">
                                <input required type="file" class="dropify" data-height="300" name="attachment" data-max-file-size="10M" data-allowed-file-extensions="pdf png jpg jpeg doc docx xls xlxs"  />
                                <br>
                            </div>
                            <div class="modal-footer">
                                <button type="button"
                                    class="btn btn-default waves-effect "
                                    data-dismiss="modal">Close</button>
                                <button type="submit"
                                    class="btn btn-success waves-effect waves-light ">Simpan</button>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </h4>
        </div>
        <div class="card-body">
            <div class="row">
                <table class="table">
                    @foreach ($attachment as $item)
            
                    <tr>
                        <td><h4>{{$loop->index+1}}. {{ $item->path }}</h4></td>
                        @if (Auth::user()->id == $data->user_id || Auth::user()->role == 'admin')
                        <td><a href="{{asset('attachment/'.$item->path)}}" download class="btn btn-warning btn-round btn-sm waves-effect waves-light text-white"><span class="fas fa-download"></span></a></td>
                            
                        @endif
                        
                    </tr>
        
                    @endforeach
                </table>
            
            </div>
        </div>
    </div>

    <div class="card">
            <div class="card-header">
                <h4>Laporan
                    @if (Auth::user()->id == $data->user_id || Auth::user()->role == 'admin')
                    <a 
                    class="btn btn-success waves-effect btn-sm float-right"
                    data-toggle="modal"
                    data-target="#report"><i class="text-white fa fa-plus-circle"></i></a>
                        
                    @endif
                    
                    <div class="modal fade" id="report" tabindex="-1"
                    role="dialog">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title"> Tambah Laporan</h4>
                                    <button type="button" class="close"
                                        data-dismiss="modal"
                                        aria-label="Close">
                                        <span
                                            aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <form action="{{route('reportevent.store')}}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                <div class="modal-body">
                                    <label for="">Laporan </label>
                                    <input type="hidden" name="event_id" value="{{$data->id}}">
                                    <input required type="file" class="dropify" data-height="300" name="report" data-max-file-size="10M" data-allowed-file-extensions="pdf doc docx xls xlxs"  />
                                    <br>
                                </div>
                                <div class="modal-footer">
                                    <button type="button"
                                        class="btn btn-default waves-effect "
                                        data-dismiss="modal">Close</button>
                                    <button type="submit"
                                        class="btn btn-success waves-effect waves-light ">Simpan</button>
                                </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <table class="table">
                        @foreach ($report as $item)
                
                        <tr>
                            <td><h4>{{$loop->index+1}}. {{ $item->path }}</h4></td>
                            @if (Auth::user()->id == $data->user_id || Auth::user()->role == 'admin')
                            <td><a href="{{asset('report/'.$item->path)}}" download class="btn btn-warning btn-round btn-sm waves-effect waves-light text-white"><span class="fas fa-download"></span></a></td>
                                
                            @endif
                            
                        </tr>
            
                        @endforeach
                    </table>
                
                </div>
            </div>
        </div>

</div>
@endsection

resources/views/pages/event2/edit.blade.php
@extends('layouts.temp')
@section('icon')
     <i class="feather icon-plus bg-c-blue"></i>
@endsection
@section('title')
    Tambah Divisi
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="#!">Divisi</a> </li>
    <li class="breadcrumb-item"><a href="#!">Tambah Divisi</a> </li>
@endsection
@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            Tambah Divisi
            <a href="{{route('divisi.index')}}" class="btn btn-secondary btn-sm float-right">Kembali</a>
        </div>
        <div class="card-body">
            <form action="{{route('divisi.update',$data)}}" method="post">
                @csrf @method('patch')
                <div class="form-group">
                    <label for="my-input">Nama</label>
                    <input id="my-input" class="form-control" type="text" name="name" required value="{{$data->name}}">
                </div>
                <button type="submit" class="btn btn-success">Edit</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/pages/event2/index.blade.php
@extends('layouts.temp')
@section('icon')
     <i class="feather icon-calendar bg-c-blue"></i>
@endsection
@section('title')
    Event
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="#!">Event</a> </li>
@endsection
@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <H3>Event</H3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 offset-md-9 col-sm-3 offset-sm-9 col-xs-3 offset-xs-9">
            <form action="" method="post">
                @csrf
                <div class="form-group ">
                    <input id="my-input" class="form-control form-control-round" type="text" name="" placeholder="Cari.....">
                </div>
            </form>
        </div>
    </div>  

@foreach ($data as $show)
    <div class="card mb-3 comp-card">
        <div class="card-body">
            <div class="row align-items-center">
                <div class="col">
                    <p class="text-secondary">{{ $show->user->name }}</p>
                    <h3 class="f-w-700 text-c-black">{{ $show->title }}
                    </h3>
                    <p>
                        @php
                            $num_char = 50 ;
                            $text = $show->description;
                            echo substr($text,0,$num_char).'.....';
                        @endphp
                    </p>
                    <p><i class="text-secondary fas fa-calendar"></i>{{ $show->start }} sd {{ $show->end }}</p>
                </div>
                <div class="col-auto mt-3 mr-2  
                ">
                   
                    @if (Auth::user()->role == 'admin')
                        @if ($show->status == 'waiting')
                            <div class="badge badge-danger">Butuh Konfirmasi</div>
                        @endif
                    @elseif (Auth::user()->role == 'user')
                        @if ($show->status == 'approve')
                            <div class="badge badge-info">Sudah Disetujui</div>
                        @elseif ($show->status == 'rejected')
                            <div class="badge badge-danger">Permintaan Ditolak</div>
                        @elseif ($show->status == 'waiting')
                            <div class="badge badge-default">Belum Dikonfirmasi</div>
                        @endif
                    @endif
                    <a href="{{route('event.show',$show)}}" class="btn btn-success btn-round btn-sm waves-effect waves-light text-white"><span class="fas fa-arrow-right"></span></a>
                    {{-- <a  class="btn btn-danger btn-sm waves-effect waves-light text-white"
                    onclick="event.preventDefault();
                    $('#delete-form').attr('action','{{route('divisi.destroy',$show)}}')
                    document.getElementById('delete-form').submit();"
                    ><span class="fas fa-trash"></span></a>
                    <form id="delete-form" action="" method="POST" style="display: none;">
                        @csrf @method('delete')
                    </form> --}}
                </div>
            </div>
        </div>
    </div>

@endforeach
{{ $data->links() }}

</div>
@endsection